[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "HAXGA1FwMfL1pgdAeexVTADUbJ6Fk3ziTWKTD9jyjfbt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ferrislav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
